const products = [
    {
        "id":1,
        "tittle":"Canon Camera",
        "image":'/images/img4.jpg',
        "price":14599,
        "ratting":4.5,
        "quantity":'5',
        "category":["tshirt","cloths"],
    },
    {
        "id":2,
        "tittle":"Canon Camera",
        "image":'/images/img8.jpg',
        "price":14599,
        "ratting":4.5,
        "quantity":'5',
        "category":["mobile","electronic"],
    },
    {
        "id":3,
        "tittle":"Canon Camera",
        "image":'/images/img3.jpg',
        "price":14599,
        "ratting":4.5,
        "quantity":'5',
        "category":["cloths","electronic"],
    },
    {
        "id":4,
        "tittle":"Canon Camera",
        "image":'/images/iPhone12.webp',
        "price":75599,
        "ratting":5,
        "quantity":'5',
        "category":["electronic","mobile"],
    },
    {
        "id":5,
        "tittle":"Canon Camera",
        "image":'/images/img5.jpg',
        "price":14599,
        "ratting":4,
        "quantity":'5',
        "category":["footwear","electronic"],
    },
    {
        "id":6,
        "tittle":"Canon Camera",
        "image":'/images/img1.jpg',
        "price":14599,
        "ratting":4.8,
        "quantity":'5',
        "category":["laptop","electronic"],
    },
    {
        "id":7,
        "tittle":"Canon Camera",
        "image":'/images/img11.jpg',
        "price":14599,
        "ratting":4.9,
        "quantity":'5',
        "category":["tablet","electronic"],
    },
    {
        "id":8,
        "tittle":"Canon Camera",
        "image":'/images/img1.jpg',
        "price":14599,
        "ratting":5,
        "quantity":'5',
        "category":["camera","electronic"],
    },
    {
        "id":9,
        "tittle":"Canon Camera",
        "image":'/images/img12.jpg',
        "price":14599,
        "ratting":3.5,
        "quantity":'5',
        "category":["electronic","laptop"],
    },
    {
        "id":10,
        "tittle":"Canon Camera",
        "image":'/images/img6.jpg',
        "price":14599,
        "ratting":4,
        "quantity":'5',
        "category":["tshirt","cloths"],
    },
]

module.exports = products;